name: Github Tieba Sign

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: yarn
      - run: node schedule.js
        env:
          BDUSS: ${{ secrets.BDUSS }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
